Space hub
Busiwa24/React-Group-Project pull request #26
Opened 2021-10-29 12:41 UTC by Busiwa24

**In the following pull request, I have completed these tasks:**
-  Built a react web application for a company that provides commercial and scientific space travel services which allow users to book rockets and join selected space missions following the set guidelines provided
- Using the SpaceX API endpoints
- Ensuring that all booking reservations are functional 
- Ensured that user data is not preserved
- I built this application solo

2021-10-29 13:27 UTC, dasileker requested changes
### **Hi @Busiwa24,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- The reducer for the mission and rocket is not storing the data retrieved from the API you can see in the video attached down.



https://user-images.githubusercontent.com/61562626/139443146-594496ae-591d-4dff-b896-db07b1b5a04d.mp4


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-29 13:27 UTC, dasileker commented on src/components/ReservedRocketList.js
> +  const filteredRockets = rockets.filter((rocket) => rocket.reserved === true);
- [ ] the reservations should e passed in react-redux reducer to store the data.

2021-10-29 17:34 UTC, helman101 requested changes
# STATUS: CHANGES REQUIRED ♻️ 

Hi @Busiwa24  👋, 

Nice work so far on this project 😄, but there are still some changes to do.

### Required Changes ♻️

- [ ] _Check the comments below_

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-29 17:34 UTC, helman101 commented on src/components/ReservedRocketList.js
> +  const filteredRockets = rockets.filter((rocket) => rocket.reserved === true);
- [ ] Since I don't see any changes on the code, I will kindly ask to work on the changes required by the previous code reviewer.
    - Please take a look at the video and the inline comments 😄 
    - I will also ask to don't submit another code review request until you have complete the require changes. 🚀

2021-10-30 11:49 UTC, DeliceLydia approved these changes
# Congratulations🎉🎉 

## Hi @Busiwa24, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard).. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-30 17:42 UTC, merged